export const addCreditNoteSchema = {
  type: 'object',
  properties: {
    invoice: { type: 'string', nullable: false, format: 'uuid' },
    gstTin: { type: 'string', nullable: false },
    creditNoteNo: { type: 'string', nullable: false },
    creditNoteDate: { type: 'string', format: 'date-time', nullable: false },
    amount: { type: 'number', nullable: false },
    sgst: { type: 'number', nullable: false },
    cgst: { type: 'number', nullable: false },
    igst: { type: 'number', nullable: false },
    total: { type: 'number', nullable: false },
    tds: { type: 'number', nullable: false },
    advance: { type: 'number', nullable: false },
    remarks: { type: 'string', nullable: true },
    month: { type: 'string', nullable: false },
  },
  required: [
    'invoice',
    'gstTin',
    'creditNoteNo',
    'creditNoteDate',
    'amount',
    'sgst',
    'cgst',
    'igst',
    'total',
    'tds',
    'advance',
    'month',
  ],
}

export const updateCreditNoteSchema = {
  type: 'object',
  properties: {
    gstTin: { type: 'string', nullable: false },
    creditNoteNo: { type: 'string', nullable: false },
    creditNoteDate: { type: 'string', format: 'date-time', nullable: false },
    amount: { type: 'number', nullable: false },
    sgst: { type: 'number', nullable: false },
    cgst: { type: 'number', nullable: false },
    igst: { type: 'number', nullable: false },
    total: { type: 'number', nullable: false },
    tds: { type: 'number', nullable: false },
    advance: { type: 'number', nullable: false },
    remarks: { type: 'string', nullable: true },
    month: { type: 'string', nullable: false },
  },
}
