export const addProformaInvoiceSchema = {
  type: 'object',
  properties: {
    campaign: { type: 'string', nullable: false, format: 'uuid' },
    gstTin: { type: 'string', nullable: false },
    billNo: { type: 'string', nullable: false },
    billDate: { type: 'string', format: 'date-time', nullable: false },
    invoiceNo: { type: 'string', nullable: false },
    invoiceDate: { type: 'string', format: 'date-time', nullable: false },
    amount: { type: 'number', nullable: false },
    sgst: { type: 'number', nullable: false },
    cgst: { type: 'number', nullable: false },
    igst: { type: 'number', nullable: false },
    total: { type: 'number', nullable: false },
    tds: { type: 'number', nullable: false },
    received: { type: 'number', nullable: false },
    balanceAmount: { type: 'number', nullable: false },
    month: { type: 'string', nullable: false },
  },
  required: [
    'campaign',
    'gstTin',
    'billNo',
    'billDate',
    'invoiceNo',
    'invoiceDate',
    'amount',
    'sgst',
    'cgst',
    'igst',
    'total',
    'tds',
    'month',
  ],
}

export const updateProformaInvoiceSchema = {
  type: 'object',
  properties: {
    gstTin: { type: 'string', nullable: false },
    billNo: { type: 'string', nullable: false },
    billDate: { type: 'string', format: 'date-time', nullable: false },
    invoiceNo: { type: 'string', nullable: false },
    invoiceDate: { type: 'string', format: 'date-time', nullable: false },
    amount: { type: 'number', nullable: false },
    sgst: { type: 'number', nullable: false },
    cgst: { type: 'number', nullable: false },
    igst: { type: 'number', nullable: false },
    total: { type: 'number', nullable: false },
    tds: { type: 'number', nullable: false },
    received: { type: 'number', nullable: false },
    balanceAmount: { type: 'number', nullable: false },
    month: { type: 'string', nullable: false },
  },
}
